---
- name: Backup Kong Configuration (DB Mode)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    pg_host: 192.168.64.128
    pg_user: kong
    pg_db: kong
    remote_backup_path: /tmp
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':','-') }}"
    local_repo_path: "{{ lookup('env','PWD') }}/project"

  tasks:

    - name: Dump Kong configuration database
      shell: >
        PGPASSWORD={{ db_password }}
        pg_dump -h {{ pg_host }} -U {{ pg_user }} {{ pg_db }}
        > {{ remote_backup_path }}/kong_config_{{ timestamp }}.sql

    - name: Fetch backup to AWX repo
      fetch:
        src: "{{ remote_backup_path }}/kong_config_{{ timestamp }}.sql"
        dest: "{{ local_repo_path }}/backups/"
        flat: yes

    - name: Git add
      delegate_to: localhost
      command: git add backups/
      args:
        chdir: "{{ local_repo_path }}"

    - name: Git commit
      delegate_to: localhost
      command: git commit -m "Kong config backup from {{ inventory_hostname }} on {{ timestamp }}"
      args:
        chdir: "{{ local_repo_path }}"
      ignore_errors: yes

    - name: Git push
      delegate_to: localhost
      command: git push
      args:
        chdir: "{{ local_repo_path }}"
