---
- name: Backup Workspace From Kong VM
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    remote_workspace_path: /opt/workspaces   # change as per your VM
    remote_backup_path: /tmp
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':','-') }}"
    local_repo_path: "{{ lookup('env','PWD') }}/project"
    local_backup_path: "{{ local_repo_path }}/backups"

  tasks:

    - name: Validate specific workspace input
      fail:
        msg: "Workspace name required for specific backup"
      when: backup_type == "Specific Workspace" and (workspace_name is not defined or workspace_name == "")

    - name: Create full backup on remote VM
      shell: >
        tar -czf {{ remote_backup_path }}/full_{{ timestamp }}.tar.gz -C {{ remote_workspace_path }} .
      when: backup_type == "Full Backup"

    - name: Create specific backup on remote VM
      shell: >
        tar -czf {{ remote_backup_path }}/{{ workspace_name }}_{{ timestamp }}.tar.gz
        -C {{ remote_workspace_path }} {{ workspace_name }}
      when: backup_type == "Specific Workspace"

    - name: Fetch backup to AWX
      fetch:
        src: "{{ remote_backup_path }}/{{ backup_type == 'Full Backup' | ternary('full_' ~ timestamp ~ '.tar.gz', workspace_name ~ '_' ~ timestamp ~ '.tar.gz') }}"
        dest: "{{ local_repo_path }}/backups/"
        flat: yes

    - name: Git add
      delegate_to: localhost
      command: git add backups/
      args:
        chdir: "{{ local_repo_path }}"

    - name: Git commit
      delegate_to: localhost
      command: git commit -m "Backup from {{ inventory_hostname }} on {{ timestamp }}"
      args:
        chdir: "{{ local_repo_path }}"
      ignore_errors: yes

    - name: Git push
      delegate_to: localhost
      command: git push
      args:
        chdir: "{{ local_repo_path }}"
