---
- name: Backup Kong Configuration (DB Mode)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    pg_host: 192.168.64.128
    pg_user: kong
    pg_db: kong
    remote_backup_path: /tmp
    local_clone_path: /tmp/kong_backup_repo
    repo_url: "https://github.com/darshanchikhalekar-cell/Kong-Workspace-Backup.git"
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':','-') }}"
    backup_file: "kong_config_{{ inventory_hostname }}_{{ timestamp }}.sql"

  tasks:

    - name: Dump Kong configuration database
      shell: >
        PGPASSWORD={{ db_password }}
        pg_dump -h {{ pg_host }} -U {{ pg_user }} {{ pg_db }}
        > {{ remote_backup_path }}/{{ backup_file }}
      args:
        executable: /bin/bash

    - name: Fetch backup to AWX temp
      fetch:
        src: "{{ remote_backup_path }}/{{ backup_file }}"
        dest: "/tmp/"
        flat: yes

    - name: Remove remote temporary backup file
      file:
        path: "{{ remote_backup_path }}/{{ backup_file }}"
        state: absent

    # -------------------------
    # Git operations (clean way)
    # -------------------------

    - name: Remove old local clone if exists
      delegate_to: localhost
      become: false
      file:
        path: "{{ local_clone_path }}"
        state: absent

    - name: Clone repository (AWX will use Source Control credential)
      delegate_to: localhost
      become: false
      git:
        repo: "{{ repo_url }}"
        dest: "{{ local_clone_path }}"
        version: main
        force: yes

    - name: Copy backup file into repo
      delegate_to: localhost
      become: false
      copy:
        src: "/tmp/{{ backup_file }}"
        dest: "{{ local_clone_path }}/backups/{{ backup_file }}"

    - name: Configure Git username
      delegate_to: localhost
      become: false
      command: git config user.name "AWX Automation"
      args:
        chdir: "{{ local_clone_path }}"

    - name: Configure Git email
      delegate_to: localhost
      become: false
      command: git config user.email "awx@demo.local"
      args:
        chdir: "{{ local_clone_path }}"

    - name: Commit changes
      delegate_to: localhost
      become: false
      command: git commit -am "Kong config backup from {{ inventory_hostname }} on {{ timestamp }}"
      args:
        chdir: "{{ local_clone_path }}"
      ignore_errors: yes

    - name: Push changes (uses existing authenticated remote)
      delegate_to: localhost
      become: false
      command: git push
      args:
        chdir: "{{ local_clone_path }}"
