---
- name: Backup Kong Configuration (DB Mode)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    pg_host: 192.168.64.128
    pg_user: kong
    pg_db: kong
    remote_backup_path: /tmp
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':','-') }}"
    local_repo_path: "/runner/project"
    backup_file: "kong_config_{{ inventory_hostname }}_{{ timestamp }}.sql"

  tasks:

    - name: Check pg_dump availability
      command: which pg_dump
      register: pg_dump_check
      failed_when: pg_dump_check.rc != 0

    - name: Dump Kong configuration database
      shell: >
        PGPASSWORD={{ db_password }}
        pg_dump -h {{ pg_host }} -U {{ pg_user }} {{ pg_db }}
        > {{ remote_backup_path }}/{{ backup_file }}
      args:
        executable: /bin/bash

    - name: Fetch backup to AWX repo
      fetch:
        src: "{{ remote_backup_path }}/{{ backup_file }}"
        dest: "{{ local_repo_path }}/backups/"
        flat: yes

    - name: Remove remote temporary backup file
      file:
        path: "{{ remote_backup_path }}/{{ backup_file }}"
        state: absent

    # -------------------------
    # Git operations on AWX node
    # -------------------------

    - name: Git add backup
      delegate_to: localhost
      become: false
      command: git add backups/
      args:
        chdir: "{{ local_repo_path }}"

    - name: Git commit
      delegate_to: localhost
      become: false
      command: git commit -m "Kong config backup from {{ inventory_hostname }} on {{ timestamp }}"
      args:
        chdir: "{{ local_repo_path }}"
      ignore_errors: yes

    - name: Git push
      delegate_to: localhost
      become: false
      command: git push
      args:
        chdir: "{{ local_repo_path }}"
